In [3]:
import tables
import numpy as np
import pandas as pd

In [4]:
file = tables.open_file("/mnt/nas/data/1s数据/stk_strN_0_endN_999.h5",mode="r")

In [5]:
print(file)

/mnt/nas/data/1s数据/stk_strN_0_endN_999.h5 (File) ''
Last modif.: '2024-05-23T21:45:45+00:00'
Object Tree: 
/ (RootGroup) ''
/datatime (EArray(10337940, 2)zlib(4)) ''
/mid (EArray(10337940, 1000)zlib(4)) ''
/stock_list (EArray(1000, 1)zlib(4)) ''
/volume (EArray(10337940, 1000)zlib(4)) ''



In [11]:
file.root.datatime[:]

array([[20210104,    93000],
       [20210104,    93001],
       [20210104,    93002],
       ...,
       [20231229,   145657],
       [20231229,   145658],
       [20231229,   145659]], dtype=int32)

In [12]:
file.root.mid[:]

array([[ 5.62 ,  6.705, 16.17 , ..., 99.15 , 58.375, 84.77 ],
       [ 5.62 ,  6.705, 16.17 , ..., 99.15 , 58.375, 84.77 ],
       [ 5.62 ,  6.705, 16.17 , ..., 99.15 , 58.335, 84.72 ],
       ...,
       [ 4.595,  4.09 ,  6.325, ..., 45.275, 53.015, 29.69 ],
       [ 4.595,  4.09 ,  6.325, ..., 45.27 , 53.015, 29.69 ],
       [ 4.595,  4.09 ,  6.325, ..., 45.27 , 53.02 , 29.69 ]],
      dtype=float32)

In [13]:
file.root.stock_list[:]

array([[     6],
       [    16],
       [    23],
       [    25],
       [   301],
       [   403],
       [   498],
       [   513],
       [   537],
       [   550],
       [   568],
       [   627],
       [   636],
       [   639],
       [   657],
       [   661],
       [   672],
       [   708],
       [   830],
       [   858],
       [   869],
       [   888],
       [   889],
       [   925],
       [   930],
       [   950],
       [   951],
       [   962],
       [   988],
       [   999],
       [  1696],
       [  2025],
       [  2032],
       [  2043],
       [  2047],
       [  2049],
       [  2058],
       [  2062],
       [  2093],
       [  2101],
       [  2110],
       [  2127],
       [  2129],
       [  2137],
       [  2146],
       [  2149],
       [  2166],
       [  2191],
       [  2211],
       [  2273],
       [  2274],
       [  2281],
       [  2308],
       [  2316],
       [  2349],
       [  2361],
       [  2371],
       [  2373],
       [  2375